### ISSUE TITLE
Review and optimize memory fences on ARM

### ISSUE THREAD

**Issue by mjansson** [mjansson/rpmalloc#142]

**Comment by Kalagon** [comment]
Hey, I guess this means optimizing the usage of `__sync_synchronize()` on ARM, is that correct?
Since this seems to be an optimization rather than a fix, could the `-Watomic-implicit-seq-cst` be temporarily disabled when building? I'm not well versed in ninja at all and currently this prevents the library from being built on my test system (RPi 2 w/ Arch, armv7l) due to `-Werror`.

I'm currently using rpmalloc as part of my thesis and would really like to include benchmarks run on a small, easy-to-obtain system for reproducability.

**Comment by mjansson** [comment]
Which ARM architecture are you referring to, ARMv7 of ARM64? Also, where does the `-Watomic-implicit-seq-cst` get added? I don't think my ninja generator adds those.

But yes, this is an optimization by folding the non-relaxed memory order into the atomic operations rather than always do relaxed and then explicit fencing.

**Comment by mjansson** [comment]
You can try it out in the mjansson/update-atomics branch

**Comment by Kalagon** [comment]
I'm using ArchLinuxARM for ARMv7.
Since the build flags include `-Wall` and `-Weverything`, I'd guess that `-Watomic-implicit-seq-cst` is implied.
Thanks, I'll try it!

**Comment by mjansson** [comment]
Let me know if you still get warnings about the implicity memory ordering and I'll try to sort it out asap

**Comment by Kalagon** [comment]
Hmm, the implicit ordering seems fixed but now there are issues regarding alignment: [Gist](https://gist.github.com/Kalagon/53d07051f9f8735114bbe117fc722edb)
Thanks for your help!

**Comment by mjansson** [comment]
I'll have a look at fixing that, for now you could turn off first class heaps to get it to compile (unless you're actively looking for that feature) ... define RPMALLOC_FIRST_CLASS_HEAPS to 0 in rpmalloc.h

**Comment by Kalagon** [comment]
Okay, the alignment errors were shadowing memory fence errors.
For now I've just edited the included ninja generator to include `-Wno-atomic-implicit-seq-cst`. Seems like the library works fine.

Having it run a bit slower isn't that much of a deal for my thesis, and I might be able to use a fixed version if it's done in the next month or so. Even if it isn't, I can just take that into account in my evaluation.

Thank you for your prompt help. If you want to have your fixes tested you can just tell me to use a newer version, then I'll just quickly run it on my test system.

**Comment by mjansson** [comment]
I'm trying to cross compile from x86-64 to arm7 and aarch64 but I don't seem to get the same errors, I guess you're using clang? I'm cross compiling with gcc at the moment

**Comment by mjansson** [comment]
Also, to speed things up a bit, could you post the various warning/error outputs you get when compiling? Including any source code line numbers

**Comment by Kalagon** [comment]
Sure:
- [this](https://gist.github.com/Kalagon/a9f4cdecc505ce71c7171c2fa82b8895) is the output of the default 1.4.0 branch
- [this](https://gist.github.com/Kalagon/b7c6a28c127102e39fc2e7782b2d6deb) is the default configuration of the `update-atomics` branch
- [this(https://gist.github.com/Kalagon/47a68a0e1e0f20a5ac9c72101565ade3) is the output on the `update-atomics` branch with first class heaps disabled

Yes, I'm using clang. Since I'm running Arch Linux ARM on the Pi it seems like the configuration doesn't use the `raspberrypi` configuration, which would seemingly use gcc by default.

**Comment by mjansson** [comment]
Right, seems to be just the test code that needs fixing apart from the alignment issue, will fix as soon as I get an hour to spare.

**Comment by mjansson** [comment]
Can you try the branch again? On a Windows machine with MSVC right no so unsure of how clang/gcc likes it though

**Comment by Kalagon** [comment]
Looks like it's working. Compilation finishes without a hitch and the tests (in `bin/release`) seem to pass:
```
[alarm@alarmpi armv7l]$ ./rpmalloc-test 
Memory allocation tests passed
Memory reallocation tests passed
Memory super aligned tests passed
Killed
[alarm@alarmpi armv7l]$ ./rpmallocwrap-test 
Allocation tests passed
Free tests passed
Allocation tests passed
Free tests passed
Allocation tests passed
Free tests passed
Thread tests passed
All tests passed
```

**Comment by mjansson** [comment]
Did you terminate the rpmalloc-test or does it deplete memory and get killed by kernel?

**Comment by Kalagon** [comment]
The process jumps up to the memory limit and freezes, then terminates. I've added a swap file so the system can keep it running a bit better. This yielded the following [results](https://gist.github.com/Kalagon/62db3245af51ad0b235eee0eaae865d7).
Strangely, I cannot find the core dump. If you'd like, I can try generating one manually, but I think this looks very much like the system kills the process due to low memory.
I don't have an ARM system with more memory right now, so I cannot tell you if it would work properly.

**Comment by mjansson** [comment]
I've reduced the 32-bit tests to map less memory
