### ISSUE TITLE
Use remaining memory from initial heaps as spans when using huge pages

### ISSUE THREAD

**Issue by romange** [mjansson/rpmalloc#171]
Hi,
First of all, thanks for this great allocation library and the fexible design! I am planning to use its plugable mmap callback functions to transparently support shared memory use-case. rpmalloc is one of the few allocators that has such ability.

Since rpmalloc already uses "heap per thread" model by default I do not event need to use first-class heaps and get everything I need using the usual `rpmalloc_thread_initialize` flow.
However, I've noticed that when rpmalloc mmaps the first block to accomodate its thread heap, it stashes the rest of its RAM for other heaps, possibly for first-class heaps even if we compile without FIRST-CLASS support. so, in case of huge pages, you use only 1.5k out of 2MB block and the rest wasted. Why did you choose this default? Why not use the same block for the initial span allocation of the heap ?

**Comment by mjansson** [comment]
Well, spans must be aligned, so the first part of that mmap:ed block would always have to be used as extra heaps to avoid waste.

Now, since spans can be retired independently of the larger super block they are part of (using MEM_DECOMMIT or POSIX_MADV_FREE) when page size is smaller than the super block size, or just waiting for the full super block to be free when we have huge pages, it would require additional logic to deal with this, which I did not have time to implement at the time.

But I agree, the best solution would be to use the aligned part of the mmap:ed block as spans for allocations, and deal with them being non-unmappable in the cache logic.

Also, there is probably improvement overall to be made when using huge pages, since then no sub-spans can be advised as decommitted/freed as they're all part of one big memory page. The cache should be aware of this and tag sibling spans as to-be-unmapped as soon as they hit the cache if one has been tagged for unmapping, to free the entire huge page as soon as possible.

**Comment by romange** [comment]
So, in other words, are you expecting non-negligible amount of wasted
memory when using huge pages in rpmalloc? Would you advise to avoid huge
pages then?

Another question, does rpmalloc ever unmaps memory if say i had a spike of
usage or it holds it in its caches forever?

**Comment by mjansson** [comment]
Well, depends on the number of threads/heaps you use, but yes, a certain amount of waste if likely. This is definitely something that needs to improve.

It does unmap excess page spans, depending on the cache size multipliers set when compiling the allocator (see the comments for the THREAD_CACHE_MULTIPLIER and GLOBAL_CACHE_MULTIPLIER defines)

**Comment by mjansson** [comment]
I've modified the title to reflect what needs improving

**Comment by romange** [comment]
@mjansson  Thank you for the extensive answer! Meanwhile, I wanted to update you that I succeeded to use rpmalloc in my concept reloadable server where it uses a dedicated rpmalloc-powered heaps with shared memory files. 

Upon process termination,
I just leave the allocated heaps hanging without making rpmalloc to unmap them. I store aside the mappings of virtual ranges to the shared-file ranges. 

Finally, I store the "root" pointers to my data-structures that manage all other objects allocated via rpmalloc heap. For example, I need to keep only a single pointer to a b-tree or a hashtable that might contain millions of objects inside. 

Upon process restart, I mmap back the same addresses that rpmalloc requested before using the kept range mappings. Instead of allocating my root data-structures from scratch I just load their pointers. As a result - we could have a database that can reload almost immediately and have RAM-based "persistency"....

**Comment by mjansson** [comment]
I've finally implemented this reuse of remainder of a huge page as spans for allocations instead of excessive number of heaps. It's available in the mjansson/huge-pages-improvements branch while I put it through some more testing.

**Comment by mjansson** [comment]
Merged to develop branch
