### ISSUE TITLE
Difference in block offset calculation

### ISSUE THREAD

**Issue by FujiZ** [mjansson/rpmalloc#188]
I found that in `_rpmalloc_heap_allocate_new()`, the address of the first heap is calculated as `pointer_offset(span, sizeof(span_t))`. However, in the rest of the code, the address of the first block in a span is `pointer_offset(span, SPAN_HEADER_SIZE)`. I wonder if this is a feature or a bug?  Will the alignment requirement be broken as the size of `span_t` grows?

**Comment by FujiZ** [comment]
I also found that `sizeof(span_t)` is only used in `_rpmalloc_heap_allocate_new()`.

**Comment by mjansson** [comment]
It's because the heap control structure  (heap_t) does not have to be aligned to SPAN_HEADER_SIZE like the normal allocation blocks, and sizeof(span_t) <= SPAN_HEADER_SIZE

But to be fair, using SPAN_HEADER_SIZE in _rpmalloc_heap_allocate_new as well might make the code a bit easier to read and understand.

**Comment by FujiZ** [comment]
Thanks for your reply!
