### ISSUE TITLE
Does it support c++?

### ISSUE THREAD

**Issue by tufeigunchu** [mjansson/rpmalloc#269]
I try to link with c++ program. But my program has static c++ map and it is initialized before rpmalloc's initializer, and crash.    
I enable "ENABLE_OVERRIDE", btw

**Comment by mjansson** [comment]
Yes, it supports C++, but doing memory allocation in global constructors is a bad idea in my opinion, since the order of initialization is not defined in any standard and is highly compiler and platform specific.

To make it work with an allocator like rpmalloc, since the order of initialization of global variables in not defined by any standard. If you are on Windows, see

https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-initialization

I made a small example for making it work with a DLL, it should be the same in an executable:

https://gist.github.com/mjansson/8a573974473e1d69a2299444cd41bea9

Or, you could add an extra check in your new/delete operators to check if rpmalloc has been initialized or not and pay the extra branch for each allocation.

**Comment by tufeigunchu** [comment]
OK. Then close issue
