### ISSUE TITLE
Cross thread allocation/deallocation bug causing crashes

### ISSUE THREAD

**Issue by nga888** [mjansson/rpmalloc#281]
I've created https://github.com/mjansson/rpmalloc/pull/280 which contains a reproducer and a couple of potential fixes for this bug.

Basically, there's a synchronisation issue between the "direct" and "deferred" deallocation of small/medium blocks. Details are provided in the above PR.

Thanks in advance for your help.

**Comment by mjansson** [comment]
There is indeed a nasty race condition where the list_size increment and load results in a double free of the span. I think the best course of action to avoid performance penalty is to opportunistically check equality in `_rpmalloc_deallocate_direct_small_or_medium` and only if list size matches used count go ahead and synchronize on the deferred pointer in order to make sure list size is accurate and that `_rpmalloc_deallocate_defer_small_or_medium` has finished updating the counter.

Could you try the mjansson/defer-race-fix branch with your test case on your machine as well? With the fix in that branch I cannot reproduce it anymore on my machine with the artificial spins.

**Comment by nga888** [comment]
Thanks for the fast response.

Yes, I think the opportunistic check makes sense to avoid the performance impact. I've suggested a slight variation on #282.

> Could you try the [mjansson/defer-race-fix](https://github.com/mjansson/rpmalloc/tree/mjansson/defer-race-fix) branch with your test case on your machine as well? With the fix in that branch I cannot reproduce it anymore on my machine with the artificial spins.

I probably won't be able to properly test any fix until Monday when I'm back to work but the approach LGTM.

Thanks!

**Comment by mjansson** [comment]
I don't see any comment, what was the suggestion?

**Comment by nga888** [comment]
> I don't see any comment, what was the suggestion?

Sorry, somehow managed to forget to hit "Submit" and it was pending. Should be there now!

**Comment by mjansson** [comment]
Fixed in #282
